PropertiesTable:
  Type: "AWS::DynamoDB::Table"
  Properties:
    TableName: Properties-${self:provider.stage}
    BillingMode: PAY_PER_REQUEST
    AttributeDefinitions:
      - AttributeName: propertyId
        AttributeType: S
      - AttributeName: ownerId
        AttributeType: S
      - AttributeName: cityLocality
        AttributeType: S
      - AttributeName: verificationStatus
        AttributeType: S
      - AttributeName: createdAt
        AttributeType: S
    KeySchema:
      - AttributeName: propertyId
        KeyType: HASH
    GlobalSecondaryIndexes:
      - IndexName: OwnerIndex
        KeySchema:
          - AttributeName: ownerId
            KeyType: HASH
        Projection:
          ProjectionType: ALL
      - IndexName: LocationStatusIndex
        KeySchema:
          - AttributeName: cityLocality
            KeyType: HASH
          - AttributeName: verificationStatus
            KeyType: RANGE
        Projection:
          ProjectionType: ALL